# Auto-generated ISO country code map for SLM code expansion
# Includes ISO 3166-1 alpha-2 and alpha-3 codes plus practical aliases.

SLM_COUNTRY_CODE_MAP = {
    "abw": "aruba",
    "ad": "andorra",
    "ae": "united arab emirates",
    "af": "afghanistan",
    "afg": "afghanistan",
    "ag": "antigua and barbuda",
    "ago": "angola",
    "ai": "anguilla",
    "aia": "anguilla",
    "al": "albania",
    "ala": "land islands",
    "alb": "albania",
    "am": "armenia",
    "and": "andorra",
    "ao": "angola",
    "aq": "antarctica",
    "ar": "argentina",
    "are": "united arab emirates",
    "arg": "argentina",
    "arm": "armenia",
    "as": "american samoa",
    "asm": "american samoa",
    "at": "austria",
    "ata": "antarctica",
    "atf": "french southern territories",
    "atg": "antigua and barbuda",
    "au": "australia",
    "aus": "australia",
    "aut": "austria",
    "aw": "aruba",
    "ax": "land islands",
    "az": "azerbaijan",
    "aze": "azerbaijan",
    "ba": "bosnia and herzegovina",
    "bb": "barbados",
    "bd": "bangladesh",
    "bdi": "burundi",
    "be": "belgium",
    "bel": "belgium",
    "ben": "benin",
    "bes": "bonaire sint eustatius and saba",
    "bf": "burkina faso",
    "bfa": "burkina faso",
    "bg": "bulgaria",
    "bgd": "bangladesh",
    "bgr": "bulgaria",
    "bh": "bahrain",
    "bhr": "bahrain",
    "bhs": "bahamas",
    "bi": "burundi",
    "bih": "bosnia and herzegovina",
    "bj": "benin",
    "bl": "saint barth lemy",
    "blm": "saint barth lemy",
    "blr": "belarus",
    "blz": "belize",
    "bm": "bermuda",
    "bmu": "bermuda",
    "bn": "brunei darussalam",
    "bo": "bolivia plurinational state of",
    "bol": "bolivia plurinational state of",
    "bq": "bonaire sint eustatius and saba",
    "br": "brazil",
    "bra": "brazil",
    "brb": "barbados",
    "brn": "brunei darussalam",
    "bs": "bahamas",
    "bt": "bhutan",
    "btn": "bhutan",
    "bv": "bouvet island",
    "bvt": "bouvet island",
    "bw": "botswana",
    "bwa": "botswana",
    "by": "belarus",
    "bz": "belize",
    "ca": "canada",
    "caf": "central african republic",
    "can": "canada",
    "cc": "cocos keeling islands",
    "cck": "cocos keeling islands",
    "cd": "democratic republic of the congo",
    "cf": "central african republic",
    "cg": "congo",
    "ch": "switzerland",
    "che": "switzerland",
    "chl": "chile",
    "chn": "china",
    "ci": "ivory coast",
    "civ": "ivory coast",
    "ck": "cook islands",
    "cl": "chile",
    "cm": "cameroon",
    "cmr": "cameroon",
    "cn": "china",
    "co": "colombia",
    "cod": "democratic republic of the congo",
    "cog": "congo",
    "cok": "cook islands",
    "col": "colombia",
    "com": "comoros",
    "cpv": "cabo verde",
    "cr": "costa rica",
    "cri": "costa rica",
    "cu": "cuba",
    "cub": "cuba",
    "cuw": "cura ao",
    "cv": "cabo verde",
    "cw": "cura ao",
    "cx": "christmas island",
    "cxr": "christmas island",
    "cy": "cyprus",
    "cym": "cayman islands",
    "cyp": "cyprus",
    "cz": "czechia",
    "cze": "czechia",
    "de": "germany",
    "deu": "germany",
    "dj": "djibouti",
    "dji": "djibouti",
    "dk": "denmark",
    "dm": "dominica",
    "dma": "dominica",
    "dnk": "denmark",
    "do": "dominican republic",
    "dom": "dominican republic",
    "dz": "algeria",
    "dza": "algeria",
    "ec": "ecuador",
    "ecu": "ecuador",
    "ee": "estonia",
    "eg": "egypt",
    "egy": "egypt",
    "eh": "western sahara",
    "er": "eritrea",
    "eri": "eritrea",
    "es": "spain",
    "esh": "western sahara",
    "esp": "spain",
    "est": "estonia",
    "et": "ethiopia",
    "eth": "ethiopia",
    "fi": "finland",
    "fin": "finland",
    "fj": "fiji",
    "fji": "fiji",
    "fk": "falkland islands",
    "flk": "falkland islands",
    "fm": "micronesia federated states of",
    "fo": "faroe islands",
    "fr": "france",
    "fra": "france",
    "fro": "faroe islands",
    "fsm": "micronesia federated states of",
    "ga": "gabon",
    "gab": "gabon",
    "gb": "united kingdom of great britain and northern ireland",
    "gbr": "united kingdom of great britain and northern ireland",
    "gd": "grenada",
    "ge": "georgia",
    "geo": "georgia",
    "gf": "french guiana",
    "gg": "guernsey",
    "ggy": "guernsey",
    "gh": "ghana",
    "gha": "ghana",
    "gi": "gibraltar",
    "gib": "gibraltar",
    "gin": "guinea",
    "gl": "greenland",
    "glp": "guadeloupe",
    "gm": "gambia",
    "gmb": "gambia",
    "gn": "guinea",
    "gnb": "guinea bissau",
    "gnq": "equatorial guinea",
    "gp": "guadeloupe",
    "gq": "equatorial guinea",
    "gr": "greece",
    "grc": "greece",
    "grd": "grenada",
    "grl": "greenland",
    "gs": "south georgia and the south sandwich islands",
    "gt": "guatemala",
    "gtm": "guatemala",
    "gu": "guam",
    "guf": "french guiana",
    "gum": "guam",
    "guy": "guyana",
    "gw": "guinea bissau",
    "gy": "guyana",
    "hk": "china hong kong special administrative region",
    "hkg": "china hong kong special administrative region",
    "hm": "heard island and mcdonald islands",
    "hmd": "heard island and mcdonald islands",
    "hn": "honduras",
    "hnd": "honduras",
    "hr": "croatia",
    "hrv": "croatia",
    "ht": "haiti",
    "hti": "haiti",
    "hu": "hungary",
    "hun": "hungary",
    "id": "indonesia",
    "idn": "indonesia",
    "ie": "ireland",
    "il": "israel",
    "im": "isle of man",
    "imn": "isle of man",
    "in": "india",
    "ind": "india",
    "io": "british indian ocean territory",
    "iot": "british indian ocean territory",
    "iq": "iraq",
    "ir": "iran islamic republic of",
    "irl": "ireland",
    "irn": "iran islamic republic of",
    "irq": "iraq",
    "is": "iceland",
    "isl": "iceland",
    "isr": "israel",
    "it": "italy",
    "ita": "italy",
    "jam": "jamaica",
    "je": "jersey",
    "jey": "jersey",
    "jm": "jamaica",
    "jo": "jordan",
    "jor": "jordan",
    "jp": "japan",
    "jpn": "japan",
    "kaz": "kazakhstan",
    "ke": "kenya",
    "ken": "kenya",
    "kg": "kyrgyzstan",
    "kgz": "kyrgyzstan",
    "kh": "cambodia",
    "khm": "cambodia",
    "ki": "kiribati",
    "kir": "kiribati",
    "km": "comoros",
    "kn": "saint kitts and nevis",
    "kna": "saint kitts and nevis",
    "kor": "republic of korea",
    "kp": "democratic people s republic of korea",
    "kr": "republic of korea",
    "ksa": "saudi arabia",
    "kw": "kuwait",
    "kwt": "kuwait",
    "ky": "cayman islands",
    "kz": "kazakhstan",
    "la": "lao people s democratic republic",
    "lao": "lao people s democratic republic",
    "lb": "lebanon",
    "lbn": "lebanon",
    "lbr": "liberia",
    "lby": "libya",
    "lc": "saint lucia",
    "lca": "saint lucia",
    "li": "liechtenstein",
    "lie": "liechtenstein",
    "lk": "sri lanka",
    "lka": "sri lanka",
    "lr": "liberia",
    "ls": "lesotho",
    "lso": "lesotho",
    "lt": "lithuania",
    "ltu": "lithuania",
    "lu": "luxembourg",
    "lux": "luxembourg",
    "lv": "latvia",
    "lva": "latvia",
    "ly": "libya",
    "ma": "morocco",
    "mac": "china macao special administrative region",
    "maf": "saint martin french part",
    "mar": "morocco",
    "mc": "monaco",
    "mco": "monaco",
    "md": "republic of moldova",
    "mda": "republic of moldova",
    "mdg": "madagascar",
    "mdv": "maldives",
    "me": "montenegro",
    "mex": "mexico",
    "mf": "saint martin french part",
    "mg": "madagascar",
    "mh": "marshall islands",
    "mhl": "marshall islands",
    "mk": "north macedonia",
    "mkd": "north macedonia",
    "ml": "mali",
    "mli": "mali",
    "mlt": "malta",
    "mm": "myanmar",
    "mmr": "myanmar",
    "mn": "mongolia",
    "mne": "montenegro",
    "mng": "mongolia",
    "mnp": "northern mariana islands",
    "mo": "china macao special administrative region",
    "moz": "mozambique",
    "mp": "northern mariana islands",
    "mq": "martinique",
    "mr": "mauritania",
    "mrt": "mauritania",
    "ms": "montserrat",
    "msr": "montserrat",
    "mt": "malta",
    "mtq": "martinique",
    "mu": "mauritius",
    "mus": "mauritius",
    "mv": "maldives",
    "mw": "malawi",
    "mwi": "malawi",
    "mx": "mexico",
    "my": "malaysia",
    "mys": "malaysia",
    "myt": "mayotte",
    "mz": "mozambique",
    "na": "namibia",
    "nam": "namibia",
    "nc": "new caledonia",
    "ncl": "new caledonia",
    "ne": "niger",
    "ner": "niger",
    "nf": "norfolk island",
    "nfk": "norfolk island",
    "ng": "nigeria",
    "nga": "nigeria",
    "ni": "nicaragua",
    "nic": "nicaragua",
    "niu": "niue",
    "nl": "netherlands",
    "nld": "netherlands",
    "no": "norway",
    "nor": "norway",
    "np": "nepal",
    "npl": "nepal",
    "nr": "nauru",
    "nru": "nauru",
    "nu": "niue",
    "nz": "new zealand",
    "nzl": "new zealand",
    "om": "oman",
    "omn": "oman",
    "pa": "panama",
    "pak": "pakistan",
    "pan": "panama",
    "pcn": "pitcairn",
    "pe": "peru",
    "per": "peru",
    "pf": "french polynesia",
    "pg": "papua new guinea",
    "ph": "philippines",
    "phl": "philippines",
    "pk": "pakistan",
    "pl": "poland",
    "plw": "palau",
    "pm": "saint pierre and miquelon",
    "pn": "pitcairn",
    "png": "papua new guinea",
    "pol": "poland",
    "pr": "puerto rico",
    "pri": "puerto rico",
    "prk": "democratic people s republic of korea",
    "prt": "portugal",
    "pry": "paraguay",
    "ps": "state of palestine",
    "pse": "state of palestine",
    "pt": "portugal",
    "pw": "palau",
    "py": "paraguay",
    "pyf": "french polynesia",
    "qa": "qatar",
    "qat": "qatar",
    "re": "r union",
    "reu": "r union",
    "ro": "romania",
    "rou": "romania",
    "rs": "serbia",
    "ru": "russian federation",
    "rus": "russian federation",
    "rw": "rwanda",
    "rwa": "rwanda",
    "sa": "saudi arabia",
    "sau": "saudi arabia",
    "sb": "solomon islands",
    "sc": "seychelles",
    "sd": "sudan",
    "sdn": "sudan",
    "se": "sweden",
    "sen": "senegal",
    "sg": "singapore",
    "sgp": "singapore",
    "sgs": "south georgia and the south sandwich islands",
    "sh": "saint helena",
    "shn": "saint helena",
    "si": "slovenia",
    "sj": "svalbard and jan mayen islands",
    "sjm": "svalbard and jan mayen islands",
    "sk": "slovakia",
    "sl": "sierra leone",
    "slb": "solomon islands",
    "sle": "sierra leone",
    "slv": "el salvador",
    "sm": "san marino",
    "smr": "san marino",
    "sn": "senegal",
    "so": "somalia",
    "som": "somalia",
    "spm": "saint pierre and miquelon",
    "sr": "suriname",
    "srb": "serbia",
    "ss": "south sudan",
    "ssd": "south sudan",
    "st": "sao tome and principe",
    "stp": "sao tome and principe",
    "sur": "suriname",
    "sv": "el salvador",
    "svk": "slovakia",
    "svn": "slovenia",
    "swe": "sweden",
    "swz": "eswatini",
    "sx": "sint maarten dutch part",
    "sxm": "sint maarten dutch part",
    "sy": "syrian arab republic",
    "syc": "seychelles",
    "syr": "syrian arab republic",
    "sz": "eswatini",
    "tc": "turks and caicos islands",
    "tca": "turks and caicos islands",
    "tcd": "chad",
    "td": "chad",
    "tf": "french southern territories",
    "tg": "togo",
    "tgo": "togo",
    "th": "thailand",
    "tha": "thailand",
    "tj": "tajikistan",
    "tjk": "tajikistan",
    "tk": "tokelau",
    "tkl": "tokelau",
    "tkm": "turkmenistan",
    "tl": "timor leste",
    "tls": "timor leste",
    "tm": "turkmenistan",
    "tn": "tunisia",
    "to": "tonga",
    "ton": "tonga",
    "tr": "turkey",
    "tt": "trinidad and tobago",
    "tto": "trinidad and tobago",
    "tun": "tunisia",
    "tur": "turkey",
    "tuv": "tuvalu",
    "tv": "tuvalu",
    "tw": "taiwan",
    "twn": "taiwan",
    "tz": "united republic of tanzania",
    "tza": "united republic of tanzania",
    "ua": "ukraine",
    "uae": "united arab emirates",
    "ug": "uganda",
    "uga": "uganda",
    "uk": "united kingdom",
    "ukr": "ukraine",
    "um": "united states minor outlying islands",
    "umi": "united states minor outlying islands",
    "ury": "uruguay",
    "us": "united states of america",
    "usa": "united states of america",
    "uy": "uruguay",
    "uz": "uzbekistan",
    "uzb": "uzbekistan",
    "va": "holy see",
    "vat": "holy see",
    "vc": "saint vincent and the grenadines",
    "vct": "saint vincent and the grenadines",
    "ve": "venezuela bolivarian republic of",
    "ven": "venezuela bolivarian republic of",
    "vg": "british virgin islands",
    "vgb": "british virgin islands",
    "vi": "united states virgin islands",
    "vir": "united states virgin islands",
    "vn": "viet nam",
    "vnm": "viet nam",
    "vu": "vanuatu",
    "vut": "vanuatu",
    "wf": "wallis and futuna islands",
    "wlf": "wallis and futuna islands",
    "ws": "samoa",
    "wsm": "samoa",
    "ye": "yemen",
    "yem": "yemen",
    "yt": "mayotte",
    "za": "south africa",
    "zaf": "south africa",
    "zm": "zambia",
    "zmb": "zambia",
    "zw": "zimbabwe",
    "zwe": "zimbabwe",
}
